# Sharp dependency issue
# https://github.com/gatsbyjs/gatsby/issues/11084

version: '3'

services:
  # gatsby:
  #   working_dir: /home/gatsby-app
  #   build:
  #     context: ./gatsby
  #     dockerfile: Dockerfile
  #   # depends_on:
  #   #   - strapi
  #   #   - db
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     GATSBY_WEBPACK_PUBLICPATH: /
  #     # STRAPI_URL: strapi:1337
  #   # command: ["gatsby", "develop"]

  strapi:
    working_dir: /home/app
    build:
      context: ./strapi
      dockerfile: Dockerfile
    environment:
      - APP_NAME=strapi-app
      - DATABASE_CLIENT=mongo
      - DATABASE_HOST=db
      - DATABASE_PORT=27017
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=
      - DATABASE_PASSWORD=
      - DATABASE_SSL=false
      - DATABASE_AUTHENTICATION_DATABASE=strapi
      - HOST=localhost
    ports:
      - 1337:1337
    volumes:
      - ./strapi:/home/app
    depends_on:
      - db
    restart: always

  db:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=strapi
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
    restart: always