# Sharp dependency issue
# https://github.com/gatsbyjs/gatsby/issues/11084

version: "3"

services:
  gatsby:
    build:
      context: ./packages/gatsby
      dockerfile: Dockerfile
    command: yarn workspace @gz-studio/gatsby develop
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - strapi
    restart: always

  strapi:
    build:
      context: ./packages/strapi
      dockerfile: Dockerfile
    environment:
      - APP_NAME=gzstudio_website
      - DATABASE_CLIENT=mongo
      - DATABASE_HOST=db
      - DATABASE_PORT=27017
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=
      - DATABASE_PASSWORD=
      - DATABASE_SSL=false
      - DATABASE_AUTHENTICATION_DATABASE=strapi
      - HOST=localhost
    ports:
      - 1337:1337
    volumes:
      - ./strapi:/usr/src/api/strapi
    #      - /usr/src/api/strapi-project/node_modules
    depends_on:
      - db
    restart: always

  db:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=strapi
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
    restart: always
